### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jmbowman** [mbnoimi/QtActionBar#1]
This looks like it could be really useful in an app I'm porting to Android, but I don't see any mention of a license.  Could you clarify that, since in a lot of jurisdictions the lack of a license means "you have no permission to use this"?  It looks like the original code by Stefan Frings is no longer online, although I'm guessing it didn't specify a license either.

It looks like you're using Qt (GPLv2+, LGPL3, or commercial) and some Material Design icons (Apache 2).  My app is GPLv2+, so the android release will probably be GPLv3+ (since Apache 2 and GPLv2 aren't compatible).

Going with about the same licensing as Qt would probably make this useful to the widest range of people, but it's really up to you (and Stefan, if we can get in touch with him).

**Comment by mbnoimi** [comment]
The original source doesn't mention its license!
http://stefanfrings.de/android_qt/index-en.html

**Comment by jmbowman** [comment]
I emailed Stefan about it, this was his response:

> Date: Sat, 04 Feb 2017 17:06:22 +0100
> Subject: AW: QtActionBar license?
> From: Stefan Frings \<address omitted\>
> To: Jeremy Bowman \<address omitted\>
> 
> Yes I removed it. Anyway do what you want with it. The code is 100% Freeware. You can also use it commercially.
> 
> Von meinem  Handy gesendet.
> 
> -------- Ursprüngliche Nachricht --------
> Von: Jeremy Bowman \<adress omitted\> 
> Datum: 04.02.17 17:01 (GMT+01:00) 
> An: \<address omitted\>
> Betreff: QtActionBar license? 
> 
> Hi, I saw in some forum posts and in a derived work at https://github.com/mbnoimi/QtActionBar that you used to have code for a Qt implementation of Android's ActionBar hosted at http://stefanfrings.de/android_qt/index-en.html .  It looks like it's been taken down, but would you mind clarifying the license for it in the discussion at https://github.com/mbnoimi/QtActionBar/issues/1 ?  I'd like to use it in an open source app I'm porting to Android, but would like to make sure it won't cause any licensing problems first.
> 
> Thanks,
> 
> Jeremy

**Comment by ghost** [comment]
I can confirm that my code is totally free.
I removed it from my homepage because I received too many help requests about Qt on Android in general.

**Comment by mbnoimi** [comment]
Hi @StefanFrings may you please create a new project of QtActionBar using your account in that way you can answer question about it and manage pull requests too.

**Comment by ghost** [comment]
No, I removed it from my homepage because I don't want to provide any
support for it.

Am 17.04.2017 um 14:49 schrieb Muhammad Bashir Al-Noimi:
